### ISSUE TITLE
Context wipe after a close

### ISSUE THREAD

**Issue by GabrielSoga** [calamar-io/calamarcopollo#1]
A lot of interference is happening due to the trip context only wiping after a reset command.
![interferencewipe](https://cloud.githubusercontent.com/assets/19688935/16475234/4e0dddac-3e53-11e6-82cb-e2390fb3ebd1.png)

A suggestion is:
- Wipe the trip context after a close (e.g.: "Obrigado!")
- Wipe the trip context after X time

**Comment by fczuardi** [comment]
> Wipe the trip context after X time

that we are already doing, the time is 15 minutes, see https://github.com/calamar-io/calamarcopollo/blob/master/src/reducer.js#L7

**Comment by GabrielSoga** [comment]
What about reducing this number to something like 1 or 2 minutes?
The current expiring time is too long if we seek to reduce interference

**Comment by fczuardi** [comment]
sounds like a plan

**Comment by GabrielSoga** [comment]
as @isadoramariamendes stated, we should wipe the context after a query fail too

**Comment by fczuardi** [comment]
I need to investigate if there is a way to differentiate between existing trips with no available bus/seats and unavailable trip routes.

For example, California, PR 🚌 Pindamonhangaba, SP is a trip not covered by Clickbus.

While Sao Carlos, SP 🚌 Sao Paulo, SP, depending on the time of the day you ask also returns 0 results but is an existing route.

Because querying the same trip on different days is something useful and if we wipe context after the first 0 results answer then the user needs to inform both origin and destination again.
